spring.application.name=twitter
server.port=8081

# Database configuration

# local db config
#spring.datasource.url=jdbc:postgresql://localhost:5432/twitter
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# render db config
spring.datasource.url=jdbc:postgresql://dpg-cvarhi2n91rc739a3n90-a:5432/twitter_vgt2
spring.datasource.username=twitter_vgt2_user
spring.datasource.password=Q9IHcbxDuW9pKmRg0R9Mr790Xieyazos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Boot Configuration
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html